FROM roba-base:latest
WORKDIR /app
COPY core ./core
COPY track_a ./track_a
COPY track_b ./track_b
COPY data ./data
RUN mkdir -p /app/dbdata
EXPOSE 8000
CMD ["uvicorn", "core.api:app", "--host", "0.0.0.0", "--port", "8000"]
